In [1]:
!pip install --upgrade kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 2.5 MB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.15-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.1.4)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 5.6 MB/s eta 0:00:00
Downloading kagglesdk-0.1.15-py3-none-any.whl (160 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 11.1 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kagglehub
  Attempting uninstall: kagglehub
    Found existing installation: kagglehub 0.3.13
    Uninstalling kagglehub-0.3.13:
      Successfully uninstalled kagglehub-0.3.13
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.15

In [2]:
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
import os
import pandas as pd
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
import kagglehub
path = kagglehub.dataset_download("rohanrao/formula-1-world-championship-1950-2020")

Using Colab cache for faster access to the 'formula-1-world-championship-1950-2020' dataset.

In [4]:
import os

path = "/kaggle/input/formula-1-world-championship-1950-2020"
os.listdir(path)

['races.csv',
 'constructor_results.csv',
 'drivers.csv',
 'constructors.csv',
 'lap_times.csv',
 'status.csv',
 'driver_standings.csv',
 'seasons.csv',
 'pit_stops.csv',
 'sprint_results.csv',
 'constructor_standings.csv',
 'results.csv',
 'circuits.csv',
 'qualifying.csv']

In [5]:
csv_file_path=os.path.join(path,'driver_standings.csv')
data=pd.read_csv(csv_file_path)

data.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [6]:
#split into input (x) and output (y) variables
x=data.iloc[:,0:6]
y=data.iloc[:,6]

In [10]:
x.dtypes

driverStandingsId      int64
raceId                 int64
driverId               int64
points               float64
position               int64
positionText          object
dtype: object

In [13]:
x = x.select_dtypes(include=['int64', 'float64'])

In [15]:
#Train-test split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
    )

In [16]:
#Feature scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(x.shape[1],)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
#compile the keras model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [19]:
#Train the model
history=model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

Epoch 1/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8695 - loss: -0.8305 - val_accuracy: 0.8347 - val_loss: -13.4604
Epoch 2/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8404 - loss: -25.9942 - val_accuracy: 0.8387 - val_loss: -82.6447
Epoch 3/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8436 - loss: -117.6358 - val_accuracy: 0.8404 - val_loss: -224.3949
Epoch 4/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8441 - loss: -301.5039 - val_accuracy: 0.8390 - val_loss: -446.4432
Epoch 5/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8424 - loss: -518.9371 - val_accuracy: 0.8340 - val_loss: -766.8481
Epoch 6/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8390 - loss: -882.4982 - val_accuracy: 0.8293 - val_loss: -1192.4233
Epoch 7/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8370 - loss: -1393.2604 - val_accuracy: 0.8351 - val_loss: -1743.0699
Epoch 8/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8449 - loss: -2180.0979 - val_accuracy: 0.8390 - val_loss: -2413.9409
Epoch 9/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8410 - loss: -2813.6853 - val_accuracy: 0.8351 - val_loss: -3270.3511
Epoch 10/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8378 - loss: -4010.0190 - val_accuracy: 0.8387 - val_loss: -4251.9961
Epoch 11/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8437 - loss: -5029.5459 - val_accuracy: 0.8383 - val_loss: -5396.7900
Epoch 12/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8452 - loss: -5779.0044 - val_accuracy: 0.8361 - val_loss: -6788.3892
Epoch 13/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8401 - loss: -8539.7910 - val_accuracy: 0.8387 - val_loss: -8306.7637
Epoch 14/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8438 - loss: -9617.5635 - val_accuracy: 0.8372 - val_loss: -10082.8232
Epoch 15/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8411 - loss: -11031.6172 - val_accuracy: 0.8379 - val_loss: -12068.6006
Epoch 16/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8457 - loss: -13273.4844 - val_accuracy: 0.8379 - val_loss: -14284.8535
Epoch 17/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8362 - loss: -17002.4766 - val_accuracy: 0.8354 - val_loss: -16858.2637
Epoch 18/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8381 - loss: -19437.3398 - val_accuracy: 0.8394 - val_loss: -19568.2090
Epoch 19/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8472 - loss: -21143.3691 - val_accuracy: 0.8358 - val_loss: -22598.2812
Epoch 20/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8420 - loss: -23605.8594 - val_accuracy: 0.8365 - val_loss: -25920.5098
Epoch 21/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8418 - loss: -29174.3750 - val_accuracy: 0.8379 - val_loss: -29508.0996
Epoch 22/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8440 - loss: -34988.9062 - val_accuracy: 0.8376 - val_loss: -33325.7070
Epoch 23/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8393 - loss: -39775.1445 - val_accuracy: 0.8379 - val_loss: -37539.1055
Epoch 24/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8394 - loss: -42740.2383 - val_accuracy: 0.8372 - val_loss: -42049.4531
Epoch 25/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8392 - loss: -52590.5664 - val_accuracy: 0.8376 - val_loss: -46894.1211
Epoch 26/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.8407 - loss: -58115.2578 - val_accuracy: 0.8379 - val_loss: -52112.5273
Epoch 27/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8387 - loss: -55329.9375 - val_accuracy: 0.8372 - val_loss: -57735.6133
Epoch 28/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8406 - loss: -69924.5391 - val_accuracy: 0.8376 - val_loss: -63666.6719
Epoch 29/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8437 - loss: -73780.6641 - val_accuracy: 0.8372 - val_loss: -69900.3750
Epoch 30/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8411 - loss: -78973.6406 - val_accuracy: 0.8379 - val_loss: -76870.1719
Epoch 31/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8443 - loss: -82266.2031 - val_accuracy: 0.8372 - val_loss: -84201.4453
Epoch 32/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8404 - loss: -97791.7969 - val_accuracy: 0.8383 - val_loss: -91755.3438
Epoch 33/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8436 - loss: -99733.2266 - val_accuracy: 0.8379 - val_loss: -99989.0547
Epoch 34/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8421 - loss: -108389.0703 - val_accuracy: 0.8383 - val_loss: -108448.9531
Epoch 35/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8402 - loss: -118607.8828 - val_accuracy: 0.8379 - val_loss: -117497.8281
Epoch 36/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8370 - loss: -123914.5547 - val_accuracy: 0.8379 - val_loss: -127240.4688
Epoch 37/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8450 - loss: -130920.3516 - val_accuracy: 0.8383 - val_loss: -137076.1875
Epoch 38/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8430 - loss: -157554.4688 - val_accuracy: 0.8383 - val_loss: -147827.2656
Epoch 39/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8393 - loss: -171908.6250 - val_accuracy: 0.8383 - val_loss: -158688.7188
Epoch 40/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8439 - loss: -165585.6719 - val_accuracy: 0.8376 - val_loss: -170151.8906
Epoch 41/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8404 - loss: -203390.3750 - val_accuracy: 0.8358 - val_loss: -182090.9844
Epoch 42/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8435 - loss: -194351.2188 - val_accuracy: 0.8376 - val_loss: -195344.2031
Epoch 43/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8415 - loss: -220832.7969 - val_accuracy: 0.8383 - val_loss: -208367.8281
Epoch 44/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8394 - loss: -243516.6250 - val_accuracy: 0.8383 - val_loss: -222123.5469
Epoch 45/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8421 - loss: -245160.5312 - val_accuracy: 0.8383 - val_loss: -236830.8594
Epoch 46/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8431 - loss: -241052.7812 - val_accuracy: 0.8383 - val_loss: -251861.2969
Epoch 47/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8426 - loss: -301147.6875 - val_accuracy: 0.8379 - val_loss: -267389.7188
Epoch 48/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8402 - loss: -307084.0312 - val_accuracy: 0.8383 - val_loss: -283375.4375
Epoch 49/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8426 - loss: -294794.2812 - val_accuracy: 0.8379 - val_loss: -300788.4688
Epoch 50/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8362 - loss: -319715.8438 - val_accuracy: 0.8383 - val_loss: -317802.1875
Epoch 51/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8407 - loss: -394368.9688 - val_accuracy: 0.8372 - val_loss: -335791.5625
Epoch 52/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8435 - loss: -423138.1250 - val_accuracy: 0.8383 - val_loss: -354292.4375
Epoch 53/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8384 - loss: -411028.1250 - val_accuracy: 0.8383 - val_loss: -374374.9062
Epoch 54/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8440 - loss: -404756.0938 - val_accuracy: 0.8383 - val_loss: -394695.4062
Epoch 55/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8428 - loss: -421200.5625 - val_accuracy: 0.8383 - val_loss: -416010.7500
Epoch 56/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8448 - loss: -407700.7188 - val_accuracy: 0.8383 - val_loss: -438270.6562
Epoch 57/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8394 - loss: -484547.3125 - val_accuracy: 0.8383 - val_loss: -460142.5938
Epoch 58/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8388 - loss: -550916.3125 - val_accuracy: 0.8383 - val_loss: -483795.5312
Epoch 59/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8408 - loss: -561636.8125 - val_accuracy: 0.8379 - val_loss: -507437.4375
Epoch 60/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8425 - loss: -554400.1875 - val_accuracy: 0.8379 - val_loss: -532550.1875
Epoch 61/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8426 - loss: -546349.0625 - val_accuracy: 0.8379 - val_loss: -558318.4375
Epoch 62/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8401 - loss: -644639.4375 - val_accuracy: 0.8383 - val_loss: -584024.5000
Epoch 63/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8432 - loss: -606167.1875 - val_accuracy: 0.8379 - val_loss: -611570.8125
Epoch 64/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8452 - loss: -652196.4375 - val_accuracy: 0.8379 - val_loss: -639511.0625
Epoch 65/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8431 - loss: -654782.0625 - val_accuracy: 0.8379 - val_loss: -668891.4375
Epoch 66/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8380 - loss: -779901.8750 - val_accuracy: 0.8376 - val_loss: -697929.1250
Epoch 67/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8398 - loss: -764128.3750 - val_accuracy: 0.8383 - val_loss: -728059.4375
Epoch 68/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8417 - loss: -830944.5625 - val_accuracy: 0.8383 - val_loss: -759693.1875
Epoch 69/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8431 - loss: -815721.5625 - val_accuracy: 0.8383 - val_loss: -793072.0000
Epoch 70/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8407 - loss: -940405.3125 - val_accuracy: 0.8379 - val_loss: -826341.9375
Epoch 71/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8419 - loss: -887848.6875 - val_accuracy: 0.8379 - val_loss: -860327.3125
Epoch 72/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8413 - loss: -909659.1250 - val_accuracy: 0.8379 - val_loss: -896082.3125
Epoch 73/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8433 - loss: -974237.9375 - val_accuracy: 0.8383 - val_loss: -931081.5625
Epoch 74/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8441 - loss: -1133768.3750 - val_accuracy: 0.8383 - val_loss: -967459.5000
Epoch 75/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8395 - loss: -1022111.2500 - val_accuracy: 0.8379 - val_loss: -1006637.4375
Epoch 76/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8441 - loss: -1138935.3750 - val_accuracy: 0.8387 - val_loss: -1044296.4375
Epoch 77/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8375 - loss: -1188159.0000 - val_accuracy: 0.8387 - val_loss: -1083728.7500
Epoch 78/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8421 - loss: -1208768.8750 - val_accuracy: 0.8383 - val_loss: -1124900.0000
Epoch 79/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8388 - loss: -1153255.0000 - val_accuracy: 0.8383 - val_loss: -1166978.8750
Epoch 80/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8402 - loss: -1265604.1250 - val_accuracy: 0.8383 - val_loss: -1209023.3750
Epoch 81/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8460 - loss: -1147708.5000 - val_accuracy: 0.8379 - val_loss: -1253467.3750
Epoch 82/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8411 - loss: -1386189.3750 - val_accuracy: 0.8383 - val_loss: -1297093.7500
Epoch 83/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8432 - loss: -1457815.1250 - val_accuracy: 0.8387 - val_loss: -1341786.5000
Epoch 84/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8428 - loss: -1514557.3750 - val_accuracy: 0.8387 - val_loss: -1388628.8750
Epoch 85/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8420 - loss: -1399661.0000 - val_accuracy: 0.8383 - val_loss: -1435878.0000
Epoch 86/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8426 - loss: -1584799.3750 - val_accuracy: 0.8383 - val_loss: -1483952.0000
Epoch 87/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8370 - loss: -1722273.0000 - val_accuracy: 0.8387 - val_loss: -1533492.7500
Epoch 88/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8381 - loss: -1696325.1250 - val_accuracy: 0.8383 - val_loss: -1584786.5000
Epoch 89/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8424 - loss: -1696474.5000 - val_accuracy: 0.8383 - val_loss: -1637135.1250
Epoch 90/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8439 - loss: -1679687.0000 - val_accuracy: 0.8379 - val_loss: -1691418.1250
Epoch 91/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8439 - loss: -1950360.0000 - val_accuracy: 0.8383 - val_loss: -1744618.2500
Epoch 92/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8374 - loss: -2012764.2500 - val_accuracy: 0.8379 - val_loss: -1799282.0000
Epoch 93/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8439 - loss: -1968168.6250 - val_accuracy: 0.8379 - val_loss: -1857243.8750
Epoch 94/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8409 - loss: -2232160.7500 - val_accuracy: 0.8379 - val_loss: -1914504.6250
Epoch 95/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8415 - loss: -2102761.2500 - val_accuracy: 0.8379 - val_loss: -1975284.3750
Epoch 96/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8404 - loss: -2259942.2500 - val_accuracy: 0.8387 - val_loss: -2032968.7500
Epoch 97/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8413 - loss: -1925263.8750 - val_accuracy: 0.8376 - val_loss: -2097644.2500
Epoch 98/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8418 - loss: -2295917.0000 - val_accuracy: 0.8387 - val_loss: -2159490.5000
Epoch 99/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8405 - loss: -2599058.7500 - val_accuracy: 0.8379 - val_loss: -2222647.5000
Epoch 100/100
1569/1569 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8376 - loss: -2540154.5000 - val_accuracy: 0.8379 - val_loss: -2288455.7500

In [20]:
#Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8302 - loss: -2505004.7500
Test Accuracy: 83.95%

In [21]:
#Make predictions
predictions = (model.predict(x_test)>0.5).astype(int)

218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [22]:
y_test = y_test.reset_index(drop=True)

In [23]:
y_test_array = y_test.values

In [24]:
y_pred = (model.predict(x_test) > 0.5).astype(int).flatten()

218/218 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [25]:
#prediction
print("Prediction:     ", y_pred[:30])
print("Actual values: ", y_test_array[:30])

Prediction:      [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0]
Actual values:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0]